"""
Data loading for PID-Net v5.

Supports:
  - Shakespeare (character-level, ~1.1M chars)
  - TinyStories (character-level, ~470M chars) — Microsoft's structured stories dataset
"""

import mlx.core as mx
import os
import json
import urllib.request
from typing import Tuple


SHAKESPEARE_URL = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
TINYSTORIES_TRAIN_URL = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStories_all_data.tar.gz"


def download_shakespeare(data_dir: str = "data") -> str:
    """Download tiny Shakespeare dataset."""
    os.makedirs(data_dir, exist_ok=True)
    path = os.path.join(data_dir, "shakespeare.txt")
    if not os.path.exists(path):
        print("Downloading Shakespeare...")
        urllib.request.urlretrieve(SHAKESPEARE_URL, path)
        print(f"Downloaded to {path}")
    return path


def download_tinystories(data_dir: str = "data", max_stories: int = 50000) -> str:
    """Download and extract TinyStories dataset.
    
    TinyStories is ~2.1M short stories generated by GPT-3.5/4.
    We download the JSON files and concatenate into a single text file.
    max_stories limits how many we use (full dataset is huge).
    """
    os.makedirs(data_dir, exist_ok=True)
    text_path = os.path.join(data_dir, f"tinystories_{max_stories}.txt")
    
    if os.path.exists(text_path):
        return text_path
    
    # Try to download individual JSON files from HuggingFace
    # TinyStories has data files like data/train-00000-of-00004.parquet
    # But easier: use the validation split which is smaller
    val_url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-valid.txt"
    train_url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"
    
    # Try the simpler text format first
    raw_path = os.path.join(data_dir, "tinystories_raw.txt")
    if not os.path.exists(raw_path):
        print("Downloading TinyStories (train split)...")
        print("This may take a few minutes (~700MB)...")
        try:
            urllib.request.urlretrieve(train_url, raw_path)
            print(f"Downloaded to {raw_path}")
        except Exception as e:
            print(f"Train download failed ({e}), trying validation split...")
            try:
                urllib.request.urlretrieve(val_url, raw_path)
                print(f"Downloaded validation split to {raw_path}")
            except Exception as e2:
                print(f"Download failed: {e2}")
                print("Please download TinyStories manually from:")
                print("https://huggingface.co/datasets/roneneldan/TinyStories")
                raise
    
    # Extract stories (separated by <|endoftext|>)
    print(f"Processing TinyStories (max {max_stories} stories)...")
    stories = []
    current_story = []
    count = 0
    
    with open(raw_path, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            if '<|endoftext|>' in line:
                if current_story:
                    story_text = ''.join(current_story).strip()
                    if len(story_text) > 50:  # skip empty/tiny stories
                        stories.append(story_text)
                        count += 1
                        if count >= max_stories:
                            break
                current_story = []
            else:
                current_story.append(line)
    
    # Handle last story
    if current_story and count < max_stories:
        story_text = ''.join(current_story).strip()
        if len(story_text) > 50:
            stories.append(story_text)
    
    # Join with separator
    full_text = '\n\n---\n\n'.join(stories)
    
    with open(text_path, 'w', encoding='utf-8') as f:
        f.write(full_text)
    
    print(f"Processed {len(stories)} stories, {len(full_text):,} chars → {text_path}")
    return text_path


class CharDataset:
    """Character-level dataset for language modeling."""
    
    def __init__(self, text: str, seq_len: int = 128):
        self.text = text
        self.seq_len = seq_len
        
        # Build vocabulary
        chars = sorted(set(text))
        self.char_to_idx = {c: i for i, c in enumerate(chars)}
        self.idx_to_char = {i: c for i, c in enumerate(chars)}
        self.vocab_size = len(chars)
        
        # Encode full text
        self.encoded = [self.char_to_idx[c] for c in text]
        
        print(f"Vocab size: {self.vocab_size}")
        print(f"Text length: {len(self.encoded):,} chars")
        print(f"Sequences: ~{len(self.encoded) // seq_len:,}")
    
    def encode(self, text: str) -> list:
        return [self.char_to_idx.get(c, 0) for c in text]
    
    def decode(self, indices) -> str:
        if hasattr(indices, 'tolist'):
            indices = indices.tolist()
        return ''.join(self.idx_to_char.get(i, '?') for i in indices)
    
    def get_batch(self, batch_size: int) -> Tuple[mx.array, mx.array]:
        """Get a random batch of sequences.
        
        Returns:
            (inputs [batch, seq_len], targets [batch, seq_len])
            where targets = inputs shifted by 1
        """
        max_start = len(self.encoded) - self.seq_len - 1
        starts = [mx.random.randint(0, max_start).item() for _ in range(batch_size)]
        
        inputs = []
        targets = []
        for s in starts:
            inputs.append(self.encoded[s : s + self.seq_len])
            targets.append(self.encoded[s + 1 : s + self.seq_len + 1])
        
        return mx.array(inputs), mx.array(targets)


def load_tinystories(seq_len: int = 256, val_split: float = 0.05, max_stories: int = 50000) -> Tuple[CharDataset, CharDataset]:
    """Load TinyStories dataset split into train/val."""
    path = download_tinystories(max_stories=max_stories)
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    
    split_idx = int(len(text) * (1 - val_split))
    train_text = text[:split_idx]
    val_text = text[split_idx:]
    
    full_dataset = CharDataset(text, seq_len)
    
    train_dataset = CharDataset(train_text, seq_len)
    train_dataset.char_to_idx = full_dataset.char_to_idx
    train_dataset.idx_to_char = full_dataset.idx_to_char
    train_dataset.vocab_size = full_dataset.vocab_size
    train_dataset.encoded = [full_dataset.char_to_idx.get(c, 0) for c in train_text]
    
    val_dataset = CharDataset(val_text, seq_len)
    val_dataset.char_to_idx = full_dataset.char_to_idx
    val_dataset.idx_to_char = full_dataset.idx_to_char
    val_dataset.vocab_size = full_dataset.vocab_size
    val_dataset.encoded = [full_dataset.char_to_idx.get(c, 0) for c in val_text]
    
    return train_dataset, val_dataset


def load_shakespeare(seq_len: int = 128, val_split: float = 0.1) -> Tuple[CharDataset, CharDataset]:
    """Load Shakespeare dataset split into train/val."""
    path = download_shakespeare()
    with open(path, 'r') as f:
        text = f.read()
    
    split_idx = int(len(text) * (1 - val_split))
    train_text = text[:split_idx]
    val_text = text[split_idx:]
    
    # Build vocab from full text, but create separate datasets
    full_dataset = CharDataset(text, seq_len)
    
    train_dataset = CharDataset(train_text, seq_len)
    # Ensure val uses same vocab
    train_dataset.char_to_idx = full_dataset.char_to_idx
    train_dataset.idx_to_char = full_dataset.idx_to_char
    train_dataset.vocab_size = full_dataset.vocab_size
    train_dataset.encoded = [full_dataset.char_to_idx[c] for c in train_text]
    
    val_dataset = CharDataset(val_text, seq_len)
    val_dataset.char_to_idx = full_dataset.char_to_idx
    val_dataset.idx_to_char = full_dataset.idx_to_char
    val_dataset.vocab_size = full_dataset.vocab_size
    val_dataset.encoded = [full_dataset.char_to_idx[c] for c in val_text]
    
    return train_dataset, val_dataset
